---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Prior to this course, I had minimal experience with coding, Over the course of the quarter, I learned how to truly think like a coder. While the idea of "learning how to think" may seem trivial, the tasks in this course pushed me to adapt a new mindset to approaching various coding problems. Over the course of this quarter, as I developed this new way of thinking through practice, I improved as a practitioner and student of data science. Particularly, I strengthened my skills in data manipulation and wrangling, writing tidy and efficient code, and creating clear, effective, and creative visualizations.

In regards to data manipulation and wrangling, I often broke down tasks and worked through problems step by step. First, I would consider what I needed to do to the data to get my desired result. Then, I would figure out the functions that could create these necessary transformations. Next, I would piece this together to apply these functions to transform the data. Shifting my mindset to think about each step needed to complete a task helped me approach data manipulation and wrangling tasks more effectively and helped me build confidence in my ability to work through more complex tasks.

As I became more comfortable with R, I began to prioritize efficiency and tidiness in my code. Within data manipulation and wrangling, This involved using one function to apply multiple conditions, such as using the mutate() function to mutate multiple columns. In challenge 3, question 1, I use the mutate() function to mutate two columns, SET_score_avg and seniority, to alter these numeric values to create new variables of the character data type. I also learned proper tidiness principles and incorporated these in my code throughout the quarter; this included using named arguments for functions, starting new lines after commas, pipe operators, and plus signs, and using white spaces around commas and arithmetic operators. This is exemplified throughout all of my labs, as I began to incorporate these principles during week 2 when we learned about tidy data.

Lastly, and most proudly, I have learned how to create strong plots and tables that display data in organized, aesthetic, and creative ways. As a creative individual, I thoroughly enjoyed incorporating colors, adjusting text size and font, including clear titles and subtitles, and adding borders. Learning how to incorporate these tools has helped me understand how to make visualizations that enhance the clarity of the data, making it easier for viewers to interpret information. This skill has allowed me to express my creativity in coding, making visualizations that are functional and engaging! Some examples of visualizations. Examples I am most proud of of my ability to create organized and creative visualizations are in labs 8 and 9, where I used knitr and gt packages as well as custom colors.
